from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import json
from pathlib import Path
from enum import Enum
import os

class Competition(str, Enum):
    titanic = "titanic"

app = FastAPI(title="MLE Dojo Status API")

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Path to the log file generated by run.py
# Assuming run.py uses the default log_dir="./experiments/logs"
LOG_FILE_PATH = Path("experiments/logs/all_log.json")

@app.get("/")
async def root():
    return {"message": "MLE Dojo Status API is running"}

@app.get("/status")
async def get_status():
    if not LOG_FILE_PATH.exists():
        raise HTTPException(status_code=404, detail="Status log file not found. Is the manager running?")
    try:
        with open(LOG_FILE_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data
    except json.JSONDecodeError:
        raise HTTPException(status_code=500, detail="Error decoding status log file")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")

@app.post("/prompt")
async def post_prompt(competition: Competition):
#some logic 
    return 

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
